### ISSUE TITLE
Legacy api LMS_GetChipTemperature sets incorrect values

### ISSUE THREAD

**Issue by davecrump** [myriadrf/LimeSuiteNG#59]
A very minor issue:

When I call  `LMS_GetChipTemperature(device, 0, &Temperature);` on a LimeSDR XTRX, it either sets Temperature as 38 or -391.  I have never seen any other values returned.

64-bit bookworm install on a LimeNET Micro 2.0 DE. LimeSuiteNG commit [8dff6c4]

Thanks, Dave

**Comment by rjonaitis** [comment]
Are you loading any custom .ini file to the device.

**Comment by davecrump** [comment]
Not sure exactly where I would load a custom .ini file, so the answer is no.

I'll load the new gateware and latest LimeSuiteNG and then provide more info.

Dave

**Comment by rjonaitis** [comment]
LMS7002m chip temperature measurement is not affected by gateware. it's done by internal ADC, https://github.com/myriadrf/LimeSuiteNG/blob/ac93854c8aafcaeb146f07dc7178d1e892ef9b88/embedded/lms7002m/lms7002m.c#L1457-L1461
I always get a value within expected range depending on cooling [39 - 52] degress. Don't know what could cause it to return -391, perhaps some chip settings affecting the internal ADC, which is why I assumed `LMS_LoadConfig` might have been used to load something.

**Comment by davecrump** [comment]
My apologies.  I have found the problem in my code.  I was checking the temperature on start-up before calling LMS_Init(device).  Calling it after the init gives the correct reading.

Dave
