### ISSUE TITLE
Transmit (GFIR) filtering seems to be Inoperative

### ISSUE THREAD

**Issue by davecrump** [myriadrf/LimeSuiteNG#79]
I have set up a test rig using a Raspberry Pi 4 and the latest version of Bookworm Lite.  I have both LimeSuite and LimeSuiteNG (commit 626a781) installed and am doing comparitive tests using a LimeSDR Mini (firmware 1.30) prior to migrating my application software on to a LimeNET Micro 2.0 DE.

The application that I am using is a DVB-S2 TV transmitter set to transmit QPSK  with a symbol rate of 4MS/s on a frequency of 437 MHz.   This is the same application that I have been using in the Portsdown ATV transmitter for many years. 

Using LimeSuite, the transmitted spectrum is what would be expected, a flat pedestal with 0.35 roll-off at the edges.  Using LimeSuiteNG, the spectrum is a sin x/x shape with the first nulls at +/- 4 MHz.  So there is clearly some digital signal processing that is not being applied in LimeSuiteNG.  It is possible to demodulate valid data from the sin x/x spectrum.

The test above was performed with no oversampling and no GFIR3 coefficients applied.  If I try to apply GFIR3 coefficients in LimeSuiteNG (with 2x opersampling), I just get a low level carrier output.  I suspect that this might be a related issue.

Spectrum views attached.

![LimeSuite](https://github.com/myriadrf/LimeSuiteNG/assets/15689285/7fee6f44-e8f1-40b8-844f-a451f67584b7)
![LimeSuiteNG](https://github.com/myriadrf/LimeSuiteNG/assets/15689285/b4236d43-ae1f-4ed9-b41b-94c52cbb2cdb)

Thanks, Dave

**Comment by rjonaitis** [comment]
Are you using `LMS_SetGFIRCoeff` to set the coefficients directly? What was used to generate the coefficients? How many coefficients is being set?

**Comment by davecrump** [comment]
I am using (LMS_SetGFIRCoeff(device, LMS_CH_TX, 0, LMS_GFIR3, xcoeffs, 119) to set the coefficients (119 of them).  xcoeffs is an array of (double) coefficients that I have been using in this application with legacy LimeSuite for 5 years.  

I have in the past (with commit https://github.com/myriadrf/LimeSuiteNG/commit/626a781f2f1d20e25b3e731f3fe8fb350a7adc97) checked that the coefficients are being entered using:

```
LMS_GetGFIRCoeff(device, LMS_CH_TX, 0, LMS_GFIR3, readout);
for (int i = 0; i < 119; i++)
{
  printf("Coeff[%d] = %.10f\n", i, readout[i]);
}

```
and they were printed correctly.

I am now unable to check anything due to Issue #91 

Thanks

Dave

**Comment by rjonaitis** [comment]
GFIR clock divider configuration was missing.

There are nuances with the GFIR coefficients configuring. Even though the absoulte maximum count of coefficients for GFIR3 is 120, the actual maximum number of coefficients used is determined by oversampling.
oversampling of 2, allows for 30 coefficients.
oversampling of 4, allows for 60 coefficients.
oversampling of 8 and higher, allows for 120 coefficients.

Another catch is that coefficients order in chip memory layout is depending on used coefficients count.
Therefore GFIR coefficients should be set after sampling rate/oversample is configured.

In legacy LimeSuite, if 2x oversample is used and 119 coefficients are being set, they all are written into chip memory, but actually only 30 coefficients would be used (not the first 30 as in the uploaded array, but 30 out fo 120 depending on chip settings).
`LMS_GetGFIRCoeff` returns all 120 coefficient registers, but they don't necessarily reflect which coefficients and in which order are being used. It's complicated. 

Which is why I was interested what was used to generate those 119 coefficients. If they were generated with standard math tools for GFIR design, then 119 coefficients would work as expected only when 8x oversampling is used.

**Comment by rjonaitis** [comment]
As alternative for uploading custom GFIR coefficients and all that complications I mentioned, there is `LMS_SetGFIRLPF` which generates and configures coefficients for desired bandwidth.
